# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/qipif/Desktop/FPGAProject/01_Preference/08_mypll/project/mypll.srcs/sources_1/ip/myfir/myfir.xci
# IP: The module: 'myfir' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/qipif/Desktop/FPGAProject/01_Preference/08_mypll/project/mypll.gen/sources_1/ip/myfir/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'myfir'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/qipif/Desktop/FPGAProject/01_Preference/08_mypll/project/mypll.gen/sources_1/ip/myfir/myfir_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myfir'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/qipif/Desktop/FPGAProject/01_Preference/08_mypll/project/mypll.srcs/sources_1/ip/myfir/myfir.xci
# IP: The module: 'myfir' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/qipif/Desktop/FPGAProject/01_Preference/08_mypll/project/mypll.gen/sources_1/ip/myfir/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'myfir'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/qipif/Desktop/FPGAProject/01_Preference/08_mypll/project/mypll.gen/sources_1/ip/myfir/myfir_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myfir'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
